apiVersion: v1
kind: Service
metadata:
  labels:
    app: model
  name: model
spec:
  ports:
  - name: "8888"
    nodePort: 30100
    port: 8888
    protocol: TCP
    targetPort: 8888
  - name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: model
  type: NodePort
status:
  loadBalancer: {}
